server:
  port: 8086
  tomcat:
    threads:
      minSpare: 10
spring:
  datasource:
    url: jdbc:mysql://172.17.6.180:3306/util_test?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  configLocation: classpath:mybatis-config.xml
#  type-aliases-package: com.example.domain.model
#  type-handlers-package: com.example.typehandler
#  configuration:
#    map-underscore-to-camel-case: true
#    default-fetch-size: 100
#    default-statement-timeout: 30
management:
  endpoints:
    shutdown:
      enable: true
    web:
      exposure:
        include: health,info,shutdown